- app/assets/stylesheets/custom.scss
- app/views/catalog/_show_assets.html.erb
- app/views/catalog/_show_tools.html.erb
- config/locales/blacklight.en.yml
- general styling for downloadable assets box on item page
- styling to ensure long file names wrap 
- styling for small screens
> Asset box design

- app/assets/javascripts/application.js
- app/assets/javascripts/readmore-call.js
- app/assets/javascripts/readmore.js
- app/assets/stylesheets/partials/item-page.scss
- app/assets/stylesheets/partials/search-results.scss
- app/views/catalog/_show_default.html.erb
- adds readmore.js jquery plugin to truncate list of author names on item pages, with option to view all names. 
https://github.com/jedfoster/Readmore.js
- for search results page, adds css to truncate author names with ellipses
> Truncate list of author names

- app/assets/javascripts/sticky-sidebar.js
- app/assets/stylesheets/partials/static-page.scss
- app/views/info/faq.html.erb
- app/views/info/policies.html.erb
I didn't realize item pages were using same sidebar id (#sidebar) as static pages, so the item page sidebar was getting fixed in an undesirable way. 
Added a unique sidebar id for static pages.
> Fixes issue where fixed sidebar was being applied to item pages

- app/assets/stylesheets/partials/facets-sidenav.scss
- app/assets/stylesheets/partials/search-results.scss
- app/controllers/catalog_controller.rb
- app/helpers/catalog_helper.rb
Styling for subjects on search results page, gives subjects a tag-like design to make them easier to scan/read.
> Span around subjects

- app/controllers/catalog_controller.rb
- lib/academic_commons.rb
- lib/academic_commons/search_parameters.rb
In AC, we make a lot of queries out to Solr outside of the blacklight controller. I wanted to create a centralized place for all these queries to be generated and executed. Right now this code uses blacklight to do the search queries, and I am okay with that for now, but my hope is that by using one method to make all these requests, if we ever were to move away from blacklight, there would be only one place in the code were we would have to update that. 
I converted one of the queries to use this new class and I wanted to get your options on it. Is there a better way to do this? What other things should I take into consideration?
Another plan I have is to use `SolrDocument#field_semantics`, to map field names like `:title` to their corresponding solr field name.
> Adding internal DSL for executing solr queries

- app/controllers/download_controller.rb
- app/controllers/solr_documents_controller.rb
- app/models/solr_document.rb
- config/routes.rb
- spec/apis/solr_documents_controller_spec.rb
- spec/controllers/download_controller_spec.rb
- spec/features/item_page_spec.rb
- spec/models/solr_document_spec.rb
- Changing download links from `/download/fedora_content/download/:uri/:block/:filename` to `/doi/:id/download`
- Removed ability to download descMetadata, no longer needed in this version of AC
- Providing redirect for old download links
> DOI in Asset Download Links

- app/controllers/collections_controller.rb
- app/views/collections/_doctoraltheses_top.erb
- app/views/collections/_journals_bottom.erb
- app/views/collections/_journals_top.erb
- app/views/collections/show.erb
Partials for text at the top or bottom of a category page can be added to views/collections. For top partial: {category_id}_top, for bottom partial {category_id}_bottom.
> Adding partials for text on collections show pages

- app/controllers/collections_controller.rb
- app/views/shared/_header_navbar.html.erb
- config/locales/blacklight.en.yml
- config/routes.rb
- spec/features/explore_spec.rb
- spec/features/homepage_spec.rb
Change the path for the collections resource to "explore"
This change should leave all the path helper and partial names intact
It adds a feature spec for the collection category pages & changes the label for the link in blacklight.en.yml
> ACHYDRA-596

- app/controllers/collections_controller.rb
- config/deploy/test.rb
- config/emails.yml
- changed explore/series url to explore/producedatcolumbia
- defaulting to branch when deploying to dev
- sending administrative emails to developer and AC staff in dev/test environments
> ACHYDRA-614

- app/api/api.rb
- app/api/v1/entities/data_feed_response.rb
- app/api/v1/entities/full_record.rb
- app/api/v1/entities/search_response.rb
- app/api/v1/entities/short_record.rb
- app/api/v1/helpers/solr.rb
- app/api/v1/record.rb
- app/controllers/catalog_controller.rb
- app/models/solr_document.rb
- app/views/info/developers.html.erb
- app/views/shared/_highwire_press_tags.erb
- app/views/shared/_social_media_tags.erb
- app/views/user/my_works.html.erb
- lib/academic_commons/search_parameters.rb
- spec/academic_commons/metrics/usage_statistics_spec.rb
- spec/api/v1/data_feed_spec.rb
- spec/api/v1/record_spec.rb
- spec/api/v1/search_spec.rb
- spec/controllers/admin/email_author_reports_controller_spec.rb
- spec/features/myworks_spec.rb
- spec/forms/email_author_reports_form_spec.rb
- spec/models/solr_document_spec.rb
- Adding resource links (partial links to assets) to API
- Documenting resource links in API docs
- Using internal search API to query Solr for API endpoint
- Solr document creates instance methods for semantic fields
- Created more efficient query to retrieve items and their related assets at the same time
> ACHYDRA-654

- config/emails.yml
Email notifications for dev and test environments were sending email to a specific developer. Now notifications for all deployed environments will be sent to an alias.
> Removing Carla from email notification

- app/controllers/catalog_controller.rb
- spec/requests/catalog_spec.rb
Fixes excessive logging problem for unhandled Blacklight::Exceptions::InvalidRequest errors.
> ACHYDRA-731: Handle catalog controller bad request with 400 bad request response

- .gitignore
- .rspec
- app/helpers/catalog_helper.rb
- app/views/catalog/_show_related_items.html.erb
- spec/catalog_helper_spec.rb
Uses 'sub' to substitute display text for two related items terms. Details for the ticket are here: https://issues.cul.columbia.edu/browse/ACHYDRA-735
> ACHYDRA-735 provides alternative text for isPreviousVersionOf and isNewVersionOf

- app/models/search_builder.rb
- spec/requests/catalog_spec.rb
In a follow-up PR, I will be adding a test of SearchBuilder's validate_sort method and I'll add a pending test to validate the per page param.
> validate requested sort fields

- app/views/catalog/_show_assets.html.erb
Item pages with multiple audio/video assets are currently generating duplicate IDs, which is causing errors with the embed code modal popups.
> Generate unique ID values for embed code modals

- app/models/concerns/academic_commons/desc_metadata.rb
this branch adds terms from 'related items' controlled vocabulary in hyacinth into ac so that they will display on the ac website if they are present in an item record
> ACHYDRA-761-new-related-items-terms

- .rubocop.yml
- Gemfile
- Gemfile.lock
- Rakefile
- config/deploy.rb
- spec/academic_commons/metrics/author_affiliation_report_spec.rb
- spec/rails_helper.rb
ACHYDRA-889: Update ci task to re-raise SystemExit exception (when present) to indicate that the tests have failed in a CI environment
And also:
- Remove coveralls
- Fix some rubocop errors
- Update rubocop expected ruby and rails version
Note: The tests on this branch are failing, but that's intentional because this branch fixes a reporting issue where failing tests were appearing as passing in CI.  This branch is just meant to be merged into the `upgrade_to_blacklight_720` branch, not the `master` branch, so we can fix the tests there before `master` merge.
> ci error reporting fix

- app/views/shared/_google_analytics.html.erb
Adds tracking code for our new GA4 account, but retains the old tracking code so we can compare results.
> Add tracking code for google analytics 4

- app/controllers/catalog_controller.rb
- spec/academic_commons/metrics/usage_statistics_spec.rb
- spec/controllers/catalog_controller_spec.rb
- lazily evaluated hash should also cache values if found to prevent double db queries
- ACHYDRA-903
> Hash subclass for featured search must override #transform_values in modern Blacklight

- Gemfile
- Gemfile.lock
- config/environments/academiccommons_prod.rb
- spec/spec_helper.rb
This will enable the X-Forwarded-For header to be usable by request.remote_ip.
> Add CUL load balancer IP to the set of trusted proxy IPs (for the academiccommons_prod environment)
