cul/ac-academiccommons

- app/controllers/catalog_controller.rb
- app/controllers/download_controller.rb
- app/controllers/sitemap_controller.rb
- app/controllers/solr_documents_controller.rb
- app/helpers/catalog_helper.rb
- app/views/catalog/_most_recent_updated.erb
- app/views/deposit/agreement_only.html.erb
- app/views/deposit/index.html.erb
- app/views/sitemap/map.xml.builder
- app/views/statistics/_statistics.html.erb
- config/routes.rb
- spec/controllers/catalog_controller_spec.rb
- spec/features/catalog_controller_spec.rb
- spec/features/deposit_spec.rb
- spec/features/sitemap_controller_spec.rb
- spec/requests/error_pages_spec.rb
- Temporary marking tests related to the front-end as pending
- Updating code to remove deprecations
- Fixing various issues with tests
> Fixing tests

- app/assets/stylesheets/bootstrap-variables.scss
- app/assets/stylesheets/custom.scss
- app/views/catalog/_search_form.html.erb
- app/views/shared/_footer.html.erb
- app/views/shared/_header_navbar.html.erb
- config/locales/blacklight.en.yml
- preview available: https://ac4-dev.cul.columbia.edu/
- not sure where to point the 'browse' link... can add that later.
> Searchbar design

- app/assets/stylesheets/custom.scss
- app/views/shared/_footer.html.erb
- adds footer links
- adds ac email link
- styling for footer
> footer design

- Gemfile.lock
- app/controllers/catalog_controller.rb
- app/helpers/catalog_helper.rb
- app/models/concerns/academic_commons/desc_metadata.rb
- app/models/concerns/academic_commons/resource.rb
- app/models/resource.rb
- app/views/catalog/_show_default.html.erb
- lib/academic_commons/indexer.rb
- solr/conf/schema.xml
- solr/conf/solrconfig.xml
- spec/fixtures/desc_metadata/access_restriction.json
- spec/fixtures/desc_metadata/etd_to_solr.json
- spec/fixtures/desc_metadata/multiple_series.json
- spec/fixtures/desc_metadata/parent_publication_names.json
- spec/fixtures/desc_metadata/subject_names_and_titles.json
- spec/fixtures/fedora_objs/actest_2.xml
- spec/fixtures/fedora_objs/actest_4.xml
- spec/fixtures/fedora_objs/to_solr.json
- spec/models/resource_spec.rb
- Updated indexing schema after feedback from staff
- Adding customization for the display of various fields on the item page
- Correctly indexing file size from RELS-INT datastream on resource
> Indexing and Display Fixes

- config/environments/ac4_test.rb
- Only happening in the ac4 test environment
> Compressing assets

- app/assets/stylesheets/modules/bootstrap-variables.scss
- app/assets/stylesheets/partials/footer.scss
- app/assets/stylesheets/partials/homepage.scss
- app/views/shared/_footer.html.erb
adds site description and links to footer based on discussion on ACHYDRA-348 ticket
> adds site description to footer

- app/assets/javascripts/application.js
Removes turbolinks to resolve conflict with author truncation js and search bar autocomplete.
> Remove turbolinks

- app/assets/stylesheets/partials/search-results.scss
- app/views/catalog/_home_text.html.erb
- app/views/catalog/_show_assets.html.erb
- app/views/shared/_footer.html.erb
Some minor updates...
- remove extraneous CUL reference in footer
- styling tweak for search results (still need to find better solution for styling subjects)
- removes Download All placeholder link
> Design updates

- app/assets/stylesheets/partials/header.scss
- app/assets/stylesheets/partials/homepage.scss
- app/views/_user_util_links.html.erb
- app/views/shared/_header_navbar.html.erb
- config/locales/blacklight.en.yml
- fixed a safari/iOS bug where searchbox was unclickable on homepage. I'm still not sure what was causing this issue, but it appeared as if something was overlapping the searchbox. when i adjusted the z-index for the searchbox (both normal and focused states), the problem went away. 
- changed 'share' to 'upload' in header, as we decided at last meeting. (https://issues.cul.columbia.edu/browse/ACHYDRA-449)
- some minor css cleanup to remove extraneous css for header
> Header fixes

- app/views/info/about.html.erb
- app/views/info/faq.html.erb
- app/views/info/policies.html.erb
Copy edits for /about, /faq, and /policies pages.
> Edits for static page content

- app/assets/javascripts/readmore-call.js
- app/assets/stylesheets/partials/item-page.scss
- app/views/info/faq.html.erb
- fixes issue where 'view more authors' was appearing in the facets navbar
- minor text edit on FAQ page
> Design fixes

- app/assets/javascripts/application.js
- app/assets/javascripts/smooth-scroll.js
- app/assets/stylesheets/partials/item-page.scss
- app/assets/stylesheets/partials/static-page.scss
- app/views/catalog/_download_button.erb
- app/views/info/faq.html.erb
- app/views/info/policies.html.erb
Adds JS for smooth-scrolling, and some css to highlight the assets panel. 
I'd like to revisit how the highlight part works (should the highlight be a momentary flash?), but I think this works for now.
> Download button functionality for multiple assets

- app/assets/javascripts/smooth-scroll.js
- app/assets/stylesheets/partials/item-page.scss
- The previous smooth scrolling javascript was not working properly in safari desktop/ios. 
- Modified the assets panel highlighting to look more like the default browser focus highlighting.
Preview available on dev.
> fixes issue with smooth scrolling in safari

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/modules/animation.scss
- app/assets/stylesheets/partials/footer.scss
- app/assets/stylesheets/partials/item-page.scss
- app/views/catalog/_show_tools.html.erb
- for small screens, the item page download button and doi will be pinned to the bottom of the screen.
> fixed position download button for mobile

- .gitignore
- app/assets/javascripts/application.js
- app/assets/javascripts/custom/add-creator.js
- app/controllers/agreements_controller.rb
- app/controllers/uploads_controller.rb
- app/models/ability.rb
- app/models/deposit.rb
- app/models/user.rb
- app/views/_user_util_links.html.erb
- app/views/catalog/_home_text.html.erb
- app/views/uploads/_agreement.html.erb
- app/views/uploads/_creator.html.erb
- app/views/uploads/index.html.erb
- app/views/uploads/new.html.erb
- app/views/uploads/successful_upload.html.erb
- config/application.rb
- config/deploy.rb
- config/initializers/okcomputer.rb
- config/routes.rb
- db/migrate/20170821153702_init_schema.rb
- db/migrate/20180404154442_create_tokens.rb
- db/migrate/20180605200128_dont_require_values_for_deposits.rb
- db/migrate/20180605201905_create_active_storage_tables.active_storage.rb
- db/migrate/20180606143542_add_columns_to_deposit.rb
- db/schema.rb
- spec/features/homepage_spec.rb
- basic form fields
- addition of ActiveStorage to manage files
- button to dynamically add more creator fields
- checking for required fields
- a Deposit can belong_to a User
- adding fields for deposit in DB table
> Beginning of Upload Form

- app/assets/stylesheets/partials/homepage.scss
- app/assets/stylesheets/partials/menu.scss
- app/views/catalog/_home_text.html.erb
- spec/features/homepage_spec.rb
- changes to homepage labels
- some html/css cleanup
> Homepage fixes

- app/assets/stylesheets/partials/item-page-sidebar.scss
- app/views/catalog/_download_and_doi.erb
- modifies template to display full doi url
- modifies styling so doi takes up full width
preview now on dev.
> Display full doi url 

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/partials/dashboard.scss
- app/assets/stylesheets/partials/static-page.scss
- app/views/uploads/_agreement.html.erb
- app/views/uploads/new.html.erb
- styling for user dashboard tabs
- styling for uploads page
> User dashboard styling

- app/controllers/admin/request_agreements_controller.rb
- app/controllers/agreements_controller.rb
- app/forms/form_object.rb
- app/forms/request_agreements_form.rb
- app/mailers/notification_mailer.rb
- app/models/agreement.rb
- app/views/admin/request_agreements/new.html.erb
- app/views/agreements/new.html.erb
- app/views/notification_mailer/request_for_agreement.html.erb
- config/routes.rb
- Adds page to request agreement from author
- Allows access to the agreement page if a valid token is passed as a parameter
> Request agreement

- app/views/info/developers.html.erb
- app/views/info/faq.html.erb
- app/views/info/policies.html.erb
Some minor text edits and typo fixes
> Text edits

- app/controllers/uploads_controller.rb
- Use the main layout on /upload for users who are not logged in
> Fix upload layout

- app/assets/stylesheets/partials/main-page.scss
- app/controllers/collections_controller.rb
- app/views/collections/show.erb
Adds blurbs and styling for blurbs in featured collections
> Blurbs for featured collections

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/partials/alert-box.scss
- app/views/layouts/blacklight.html.erb
- app/views/shared/_alert_box.erb
- app/views/shared/_cul_banner.erb
- app/views/shared/_header_navbar.html.erb
> Alert box design

- app/assets/javascripts/upload/license-options.js
- app/views/uploads/new.html.erb
Text edits and light styling for copyright and licensing info, for the purposes of adding clarity and consistency.
> word edits for upload form

- app/assets/stylesheets/partials/dashboard.scss
Modifies the hover effect on sortable lists. Now the whole row is highlighted and the cursor turns into a directional arrow. Hopefully this makes it more obvious that the row is draggable. 
Preview on dev.
> redesign sortable hover effect

- app/assets/javascripts/application.js
- app/assets/javascripts/copy-to-clipboard.js
- app/assets/stylesheets/partials/item-page-sidebar.scss
- app/views/catalog/_download_and_doi.erb
- app/views/catalog/_download_button.erb
- package.json
- yarn.lock
Add copy-to-clipboard for item page DOIs and enables bootstrap tooltips. 
https://yarnpkg.com/en/package/clipboard
> Copy to clipboard

- app/controllers/user_controller.rb
> Checking for the present of deposits and hyacinth identifiers

- app/models/solr_document.rb
- spec/models/solr_document_spec.rb
This is in effort to reduce our solr traffic
> Only querying for assets once

- app/assets/javascripts/application.js
- app/assets/javascripts/flash-messages-for-ajax-requests.js
- app/controllers/admin/email_preferences_controller.rb
- app/controllers/solr_documents_controller.rb
- app/controllers/uploads_controller.rb
- app/controllers/user_controller.rb
- app/forms/email_author_reports_form.rb
- app/models/ability.rb
- app/models/email_preference.rb
- app/models/user.rb
- app/views/admin/email_preferences/_form.html.erb
- app/views/admin/email_preferences/index.html.erb
- app/views/admin/email_preferences/show.html.erb
- app/views/statistics_mailer/_monthly_footer.html.erb
- app/views/user/account.html.erb
- db/migrate/20181012171010_rename_columns_and_add_constraints_to_email_preferences.rb
- db/schema.rb
- spec/controllers/admin/email_preferences_controller_spec.rb
- spec/controllers/user_controller_spec.rb
- spec/features/myaccount_spec.rb
- spec/models/email_preference_spec.rb
Adding ability for users to edit preferred email or opt out of emails.
> ACHYDRA-502 User Email Preferences

- app/helpers/homepage_helper.rb
- app/views/catalog/_home_text.html.erb
> use titlecase genre/type links in front page stats and links

- app/forms/email_author_reports_form.rb
- app/models/email_preference.rb
- lib/academic_commons.rb
- lib/tasks/ac.rake
- Adding rake task to generate CSV of author emails
> ACHYDRA-686

- app/assets/javascripts/application.js
- app/assets/javascripts/skip-link-focus-fix.js
- app/assets/javascripts/upload/add-creator.js
- app/assets/stylesheets/global.scss
- app/assets/stylesheets/modules/bootstrap-variables.scss
- app/assets/stylesheets/partials/dashboard.scss
- app/assets/stylesheets/partials/footer.scss
- app/assets/stylesheets/partials/homepage.scss
- app/assets/stylesheets/partials/item-page.scss
- app/assets/stylesheets/partials/main-page.scss
- app/assets/stylesheets/partials/menu.scss
- app/views/catalog/_doi.erb
- app/views/layouts/admin.html.erb
- app/views/layouts/blacklight.html.erb
- app/views/layouts/dashboard.html.erb
- app/views/layouts/main.erb
- app/views/shared/_cul_banner.erb
- app/views/shared/_footer.html.erb
- app/views/shared/_header_navbar.html.erb
- app/views/uploads/new.html.erb
https://issues.cul.columbia.edu/browse/ACHYDRA-706
> Accessibility fixes

- app/helpers/asset_helper.rb
- app/views/catalog/_show_assets.html.erb
- fixes issue with scrollbars appearing with video embeds
- fixes accessibility issue with video embed iframes
> Video player embed fixes

- app/models/concerns/academic_commons/desc_metadata.rb
- app/models/solr_document.rb
- spec/fixtures/desc_metadata/related_items.xml
- spec/fixtures/fedora_objs/mods.xml
- spec/models/solr_document_spec.rb
- spec/spec_helper.rb
isIdenticalTo, references, referencedBy; Also added fallback display behavior for related item with no title
> Added additional related item types (for indexing and display)

- app/assets/stylesheets/partials/alert-box.scss
- app/views/shared/_alert_box.erb
DS would like the ability to add links to the alert box messages.
> Allow html in alert messages (ACHYDRA-868)

- Gemfile
- Gemfile.lock
- app/controllers/admin/agreements_controller.rb
- app/controllers/admin/deposits_controller.rb
- app/javascript/stylesheets/partials/admin.scss
- app/views/admin/agreements/index.html.erb
- app/views/admin/deposits/index.html.erb
Implemented pagination on agreements and deposits pages. Currently implemented using the `will_paginate` gem, but can be fairly easily changed to use another gem if preferred.
> Achydra 632

- app/views/info/faq.html.erb
Updates to FAQ to assist copyright holders of works in AC
> dissertation plagiarism update faq.html.erb 

- app/views/info/developers.html.erb
- app/views/info/faq.html.erb
- app/views/info/policies.html.erb
@barmintor , would you be willing to review these to make sure I'm not saying anything out of turn? same language as what was shared in our meeting. ty.
> updates to info pages to reflect policy on llm-training
